// Studio 生成工具卡片配置
import type { StudioToolCard } from '@/types/notebook'

export const STUDIO_TOOL_CARDS: StudioToolCard[] = [
  // —— Insight 洞察类 ——
  {
    type: 'audio_overview',
    name: '音频概览',
    description: '用语音方式快速浏览资料要点',
    icon: 'sound',
    category: 'insight',
    prompt: '请基于当前对话和选择的来源资料，生成一段2-3分钟的语音播客风格概览，用自然流畅的口语串联核心要点。',
    supportedSources: ['documents', 'knowledge_base'],
  },
  {
    type: 'report',
    name: '研究报告',
    description: '生成结构化的深度研究报告',
    icon: 'file-copy',
    category: 'insight',
    prompt: '请基于当前对话上下文和选择的来源资料，撰写一份结构化的深度研究报告。包含：摘要、背景、核心发现、数据分析、结论与建议等章节，使用 Markdown 格式。',
    supportedSources: ['documents', 'conversation', 'knowledge_base'],
  },
  {
    type: 'video_script',
    name: '视频脚本',
    description: '基于资料生成旁白与画面脚本',
    icon: 'video',
    category: 'insight',
    pro: true,
    prompt: '请基于当前来源资料，撰写一个3-5分钟的视频脚本。包含场景描述、旁白台词、画面提示，按时间线分段落组织。',
    supportedSources: ['documents', 'knowledge_base'],
  },
  {
    type: 'briefing',
    name: '简报',
    description: '一页纸快速掌握核心信息',
    icon: 'layers',
    category: 'insight',
    prompt: '请基于来源资料生成一份一页纸简报，用最精炼的语言呈现：核心结论（3条以内）、关键数据、行动建议（3条以内）。',
    supportedSources: ['documents', 'conversation', 'knowledge_base'],
  },

  // —— Organize 整理类 ——
  {
    type: 'outline',
    name: '大纲',
    description: '自动梳理资料的层次结构',
    icon: 'view-list',
    category: 'organize',
    prompt: '请基于来源资料生成一份层次分明的大纲，使用 Markdown 多级标题结构（#/##/###），覆盖所有重要主题和子主题。',
    supportedSources: ['documents', 'conversation', 'knowledge_base'],
  },
  {
    type: 'mind_map',
    name: '思维导图',
    description: '以脑图形式展现核心概念与关系',
    icon: 'git-branch',
    category: 'organize',
    prompt: '请基于来源资料生成思维导图结构，使用 Markdown 缩进列表格式。以中心主题为根节点，展开3-4级分支，展示概念之间的层级关系。',
    supportedSources: ['documents', 'conversation', 'knowledge_base'],
  },
  {
    type: 'timeline',
    name: '时间线',
    description: '按时间顺序整理关键事件',
    icon: 'time',
    category: 'organize',
    prompt: '请基于来源资料，按时间先后顺序整理关键事件时间线。格式：**日期/时间** - 事件描述 - 意义/影响',
    supportedSources: ['documents', 'knowledge_base'],
  },
  {
    type: 'data_table',
    name: '数据表格',
    description: '将关键信息整理为结构化表格',
    icon: 'chart-column',
    category: 'organize',
    prompt: '请从来源资料中提取关键信息，整理为 Markdown 表格。选择合适的维度（如：名称/指标/数值/说明，或 方案/优点/缺点/适用场景等）。',
    supportedSources: ['documents', 'conversation', 'knowledge_base'],
  },
  {
    type: 'glossary',
    name: '术语表',
    description: '提取专业术语并给出定义',
    icon: 'book',
    category: 'organize',
    prompt: '请从来源资料中提取所有重要的专业术语、缩写和关键概念，整理为术语表。格式：**术语** —— 简明定义（一句话说明）',
    supportedSources: ['documents', 'knowledge_base'],
  },

  // —— Create 创作类 ——
  {
    type: 'presentation',
    name: '演示文稿',
    description: '自动生成幻灯片结构与内容',
    icon: 'slideshow',
    category: 'create',
    pro: true,
    prompt: '请基于来源资料生成一份演示文稿大纲，包含10-15页幻灯片。每页格式：## 幻灯片标题\n- 要点1\n- 要点2\n- 要点3\n\n包含封面、目录、内容章节、总结页。',
    supportedSources: ['documents', 'conversation', 'knowledge_base'],
  },
  {
    type: 'infographic',
    name: '信息图',
    description: '将数据和要点可视化呈现',
    icon: 'chart-pie',
    category: 'create',
    pro: true,
    prompt: '请基于来源资料，用 Mermaid 图表或 ASCII 图的方式呈现关键数据关系和核心要点，配合简洁的文字说明，使其适合制作信息图。',
    supportedSources: ['documents', 'knowledge_base'],
  },
  {
    type: 'summary',
    name: '摘要',
    description: '精炼长文为简短摘要',
    icon: 'text',
    category: 'create',
    prompt: '请基于当前对话上下文和来源资料，生成一份简洁的摘要（300字以内），包含核心主题、关键观点和最重要的结论。',
    supportedSources: ['documents', 'conversation', 'knowledge_base'],
  },
  {
    type: 'transcript',
    name: '文字稿',
    description: '将音频/视频内容转为文字',
    icon: 'file-text',
    category: 'create',
    prompt: '请对上传的音频/视频资料进行转写整理，生成结构化的文字稿，标注发言人、时间节点和关键内容。',
    supportedSources: ['documents'],
  },

  // —— Study 学习类 ——
  {
    type: 'flashcards',
    name: '闪卡',
    description: '自动生成问答卡片辅助记忆',
    icon: 'layers',
    category: 'study',
    prompt: '请基于来源资料生成10-15张学习闪卡，格式：\n\n**问**：问题\n**答**：答案\n\n问题覆盖核心概念、关键事实、重要定义。',
    supportedSources: ['documents', 'knowledge_base'],
  },
  {
    type: 'quiz',
    name: '测验题',
    description: '生成选择题检验理解程度',
    icon: 'check-circle',
    category: 'study',
    prompt: '请基于来源资料生成10道选择题，每题包含4个选项（A/B/C/D），标注正确答案并给出简要解析。',
    supportedSources: ['documents', 'knowledge_base'],
  },
  {
    type: 'study_guide',
    name: '学习指南',
    description: '规划系统的学习路径',
    icon: 'user-guide',
    category: 'study',
    prompt: '请基于来源资料设计一份系统的学习指南，包含：学习目标、先修知识、分阶段学习计划（入门/进阶/精通）、推荐练习、自测要点。',
    supportedSources: ['documents', 'knowledge_base'],
  },
  {
    type: 'faq',
    name: '常见问题',
    description: '自动提取高频问题与答案',
    icon: 'help',
    category: 'study',
    prompt: '请基于来源资料和常见疑问，生成一份 FAQ 文档。列出8-12个高频问题，每个问题给出清晰、准确的回答。格式：\n\n**Q: 问题**\nA: 回答',
    supportedSources: ['documents', 'conversation', 'knowledge_base'],
  },
  {
    type: 'key_quotes',
    name: '关键引语',
    description: '摘录最有价值的原文片段',
    icon: 'chat',
    category: 'study',
    prompt: '请从来源资料中摘录10-15条最有价值、最具代表性的原文引语，按主题分类，每条注明出处章节。',
    supportedSources: ['documents', 'knowledge_base'],
  },

  // —— Share 分享类 ——
  {
    type: 'comparison',
    name: '对比分析',
    description: '对比多个方案/观点的异同',
    icon: 'difference',
    category: 'share',
    prompt: '请基于来源资料进行对比分析。使用 Markdown 表格呈现多个方案/观点在关键维度上的异同，包含对比维度、各方特点、优缺点总结，最后给出选择建议。',
    supportedSources: ['documents', 'conversation', 'knowledge_base'],
  },
  {
    type: 'action_items',
    name: '行动项',
    description: '从讨论中提取待办与责任人',
    icon: 'check-circle-filled',
    category: 'share',
    prompt: '请从当前对话内容中提取所有明确的行动项/待办事项。格式：\n\n- [ ] **任务描述** —— 负责人（如有） —— 截止时间（如有）\n\n按优先级排序。',
    supportedSources: ['conversation', 'documents'],
  },
]

/** 分类展示顺序与中文名 */
export const STUDIO_CATEGORIES: Array<{ id: string; name: string }> = [
  { id: 'insight', name: '洞察' },
  { id: 'organize', name: '整理' },
  { id: 'create', name: '创作' },
  { id: 'study', name: '学习' },
  { id: 'share', name: '分享' },
]
